import { ResumeProfile } from '@/types/resume'

/**
 * A deterministic mock parser that simulates AI extraction.
 * It scans the extracted text for predefined keywords.
 */
export async function generateMockProfile(text: string): Promise<ResumeProfile> {
  // Simulate AI delay
  await new Promise((resolve) => setTimeout(resolve, 800))

  const lowerText = text.toLowerCase()

  const detectSkills = () => {
    const commonTechs = [
      'react', 'next.js', 'javascript', 'typescript', 'node.js',
      'laravel', 'php', 'mysql', 'postgresql', 'rest api',
      'angular', 'html', 'css', 'git', 'docker'
    ]

    return commonTechs.filter(tech => lowerText.includes(tech))
  }

  const technical_skills = detectSkills()

  let professional_title = 'Software Professional'
  if (lowerText.includes('frontend') || lowerText.includes('front-end')) professional_title = 'Frontend Developer'
  else if (lowerText.includes('backend') || lowerText.includes('back-end')) professional_title = 'Backend Developer'
  else if (lowerText.includes('fullstack') || lowerText.includes('full-stack')) professional_title = 'Full Stack Developer'

  // Look for a possible name in the first few lines
  const lines = text.split('\n').map(l => l.trim()).filter(l => l.length > 0)
  const full_name = lines.length > 0 ? lines[0] : 'Unknown Name'

  return {
    full_name,
    professional_title,
    summary: 'A highly motivated professional with experience in software development. (This is a mock summary generated by the local deterministic parser).',
    skills: [...technical_skills, 'Problem Solving', 'Teamwork'],
    technical_skills,
    soft_skills: ['Problem Solving', 'Teamwork', 'Communication'],
    experience: [
      {
        job_title: professional_title,
        company: 'Tech Solutions Inc.',
        start_date: '2020-01-01',
        end_date: 'Present',
        description: 'Developed and maintained various web applications using modern technologies found in the resume.',
        technologies: technical_skills.slice(0, 3)
      }
    ],
    education: [
      {
        degree: 'Bachelor of Science in Computer Science',
        institution: 'University of Technology',
        start_date: '2015-08-01',
        end_date: '2019-05-01'
      }
    ],
    projects: [
      {
        name: 'Portfolio Project',
        description: 'A personal portfolio to showcase technical skills and projects.',
        technologies: technical_skills.slice(0, 2)
      }
    ],
    certifications: ['AWS Certified Developer (Mock)'],
    total_experience_years: 4,
    locations: ['Remote', 'Local City']
  }
}
