export interface Signature {
  fullName: string;
  email: string;
  phone: string;
  location: string;
  portfolioUrl: string;
  linkedinUrl?: string;
}

export interface WorkingWebsite {
  id: string;
  name: string;
  url: string;
  description: string;
}

export interface Resume {
  name: string;
  base64Data: string; // The base64 encoded PDF string
  parsedText?: string; // The extracted text content for the AI to use
}

export type JobApplicationStatus = "draft" | "generated" | "sent" | "error";

export interface JobApplication {
  id: string;
  inputSource: "text" | "file";
  originalInput: string;
  
  // Extracted by AI
  jobTitle?: string;
  company?: string;
  recipientEmail?: string;
  alternateContact?: string;
  recruiterName?: string;
  requirements?: string;

  // Generated by AI
  generatedSubject?: string;
  generatedBody?: string;
  selectedWebsiteId?: string;

  status: JobApplicationStatus;
  createdAt: number;
}
