export interface Signature {
  fullName: string;
  email: string;
  phone: string;
  location: string;
  portfolioUrl: string;
  linkedinUrl?: string;
}

export interface WorkingWebsite {
  id: string;
  name: string;
  url: string;
  description: string;
}

export interface AutoScoutPreferences {
  keywords: string;
  location: string;
  mode: "fulltime" | "freelance";
  source: "web" | "linkedin" | "naukri" | "indeed" | "custom";
  timeRange?: "past_24h" | "past_week" | "past_month" | "any";
}

export interface Resume {
  name: string;
  base64Data: string; // The base64 encoded PDF string
  parsedText?: string; // The extracted text content for the AI to use
}

export type JobApplicationStatus = "draft" | "generated" | "sent" | "manually_applied" | "error";

export interface JobApplication {
  id: string;
  inputSource: "text" | "file" | "scraper";
  originalInput: string;
  
  // Extracted by AI
  jobType?: "fulltime" | "freelance";
  jobTitle?: string;
  company?: string;
  jobUrl?: string;
  recipientEmail?: string;
  alternateContact?: string;
  recruiterName?: string;
  requirements?: string;

  // Generated by AI
  generatedSubject?: string;
  generatedBody?: string;
  selectedWebsiteId?: string;

  status: JobApplicationStatus;
  createdAt: number;
}

export interface AutoScoutLead {
  id: string;
  source: string;
  jobTitle: string;
  company: string;
  location: string;
  jobUrl: string;
  fullDescription: string;
  recipientEmail?: string;
  phone?: string;
  applicationUrl?: string;
  recruiterName?: string;
  matchScore?: number;
  status: 'new' | 'applied' | 'no_email' | 'failed';
  firstSeenAt: number;
  lastSeenAt: number;
  appliedAt?: number;
  errorReason?: string;
}
